version: '3.9'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DATABASE_URL=/data/memo.db
      - APP_BEARER_TOKEN=${APP_BEARER_TOKEN}
    volumes:
      - ./data:/data
